# general settings
name: MedVSR_Train
model_type: VideoRecurrentModel
scale: 4
num_gpu: 2
manual_seed: 0
find_unused_parameters: false
use_static_graph: true
# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: HKRecurrentDataset
    dataroot_gt: ./hyperkvasir_train/GT
    dataroot_lq: ./hyperkvasir_train/BIx4
    meta_info_file: ./meta_info_hyperkvasir.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    test_mode: False
    io_backend:
      type: disk

    num_frame: 6
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: REDS4
    type: VideoRecurrentTestDataset
    dataroot_gt: ./hyperkvasir_val/GT
    dataroot_lq: ./hyperkvasir_val/BIx4

    cache_data: true
    io_backend:
      type: disk

    num_frame: -1  # not needed

# network structures
network_g:
  type: MedVSR
  mid_channels: 64
  num_blocks: 7
  is_low_res_input: true
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth
  prop_progressive: false
  n_mambablocks: 1
  conv_first: false
  mamba_block_version: v1_mamba2simplecat
  n_convfe: 5
  n_convrec: 10
  fe_type: normal
  trunk_type: normal
  rec_type: hybrid
  rec_dw: true
  rec_dw_version: v1
  rec_ks: 7
  flow_warp: true
  cross_arc_order: second
  cross_arc: prop_cond_after # prop_cond_after
  local_window: true
  window_size: 16
  use_pe: on_c # only used on local windows
  arc_mixer: mamba2_gate
  num_additional_blocks: 0
  share_conv1d: false
  deform_align_duo_flow_n1: true
  deform_align_use_feat_cur_n1_n2: n1
  # norm_layer: nn.Identity
  Mlp_block: GatedMlp


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
  experiments_root: ./vsr_experiments/hyperkvasir

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [100000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 100000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean


# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
# logging settings
logger:
  print_freq: 1
  checkpoint_save_start_iter: 50000
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 25624


find_unused_parameters: true